### ISSUE TITLE
Can't add a snippet

### ISSUE THREAD

**Issue by claudio-dalicandro** [sulu-io/docs#17]
Following the doc (https://github.com/sulu-io/docs/blob/master/developer-documentation/300-webspaces/snippets.md) I put the XML file for the type of snippets that I need, without worrying to create a corresponding template, the documentation does not say anything (and if I understand correctly the nature of the snippets actually does not need to have a template...) but I get this error:

```
app.WARNING: a valid template with key "layout_info" and file "/<PATH>/app/Resources/snippets/layout_info.xml" cannot be found 
```

**Comment by dantleech** [comment]
The `key` element in the XML file needs to be `layou_info` also. If this does not work could you create a gist with your template?

**Comment by claudio-dalicandro** [comment]
Damn, I was sure I changed the key field! I apologize for the waste of time!

**Comment by dantleech** [comment]
No problem, the exception message is less than crystal clear, I created a new [issue](https://github.com/sulu-io/sulu/issues/1266).
